Foreground true
LogTime true
LogSyslog false
DatabaseDirectory /var/lib/clamav
LocalSocket /tmp/clamd.sock
TCPSocket 3310
TCPAddr 127.0.0.1
MaxThreads 4
MaxConnectionQueueLength 16
StreamMaxLength 30M
MaxScanSize 30M
MaxFileSize 30M
User root
