steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform=linux/amd64
      - -f
      - apps/ai-service/Dockerfile
      - -t
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}

substitutions:
  _IMAGE: europe-west3-docker.pkg.dev/spb-ai/spb-services/ai-service:staging
